name: Create or Update dev->main PR (Monorepo)

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
    paths:
      - 'monorepo/**'

defaults:
 run:
  working-directory: ./monorepo

jobs:
  create-or-update-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install dependencies
        run: |
          yarn add @octokit/rest ts-node typescript @types/node -W

      - name: Run TypeScript script
        run: node ./scripts/test.js
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
