name: npm
env:
  CI: true
on:
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Configure Git
        run: |
          git config --global user.name 'Pangolin'
          git config --global user.email 'pangolindex@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn --frozen-lockfile
        env:
          CI: true
      - name: Prod - Increment version & create build # incrementing version automatically creates build internally with new version
        run: npm version patch -m "[skip ci] %s"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CI: false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      # create env file from secrets
      - run: echo "${{ secrets.ENV_FILE }}" > .env

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
