name: Publish beta package
on:
  pull_request:
    branches:
      - main1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16.x'

      - run: yarn --frozen-lockfile
        env:
          CI: true

      # Update package version to a beta release, including the git commit sha
      - name: Bump package.json
        run: |
          npm --no-git-tag-version version $(npm show . version)-beta.$(git rev-parse --short HEAD)

      # Publish version to npm
      - name: Publish beta package
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
